[build]
  # This site is purely static; no build step required.
  command = ""
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"

[[redirects]]
  # Route any path under /admin to the admin HTML page so that deep links work
  from = "/admin/*"
  to = "/admin.html"
  status = 200